Translations
Quantum-Game/quantum-game-2 pull request #225
Opened 2020-09-04 09:17 UTC by Frizi

This is a showcase implementation for translation system. Currently only Options page is translated. More changes would be needed across the app to properly translate everything.

Features include:
- detecting and using default browser language
- language switcher in options
- preserving manually chosen language in localStorage

For users of VSCode, I recommend installing [I18n Ally] extension and adding this config to your local project .vscode/settings.json:
```json
{
    "i18n-ally.localesPaths": [
        "src/i18n/locales"
    ],
    "i18n-ally.enabledParsers": [
        "ts"
    ],
    "i18n-ally.keystyle": "nested"
}
```

This allows for preview and jump-to-definition of translated text in-code among other things.

![image](https://user-images.githubusercontent.com/919491/92220967-063a9480-ee9d-11ea-8a22-e4f689090eff.png)

[I18n Ally]: https://marketplace.visualstudio.com/items?itemName=antfu.i18n-ally

2020-09-04 10:56 UTC, stared commented
If we can do it gradually, yes!

Sooner or later we want to have translations. Plus, separating text from other pieces of code is a plus for me.

@KlemKlem What you think about this feature for translations?

2020-09-05 08:30 UTC, KlemKlem commented
Sounds great! although I am not sure when we get to different language versions.

2020-09-05 12:23 UTC, stared commented on .gitignore
> +
This should be a separate commit. 

fix(gitignore) package-lock.json not tracked

2020-09-05 12:25 UTC, stared commented on src/i18n/pluralizationRules.ts
> +function slavicPluralization(choice: number, choicesLength: number): number {
This clearly requires a TSDoc comment.

2020-09-05 12:26 UTC, stared requested changes
Yes, we want to have it. A small docstring would be needed, otherwise let's start using that.

2020-09-07 10:30 UTC, stared approved these changes

2020-09-07 10:30 UTC, merged