Qt gluecode (WIP)
Quantum-Game/quantum-game-2 pull request #226
Opened 2020-09-04 22:32 UTC by sneakyweasel

The game is working smoothly with a very nice performance increase, this PR is mostly to discuss a few things:

- Grid information is sent to qt in JSON format and there is a mismatch between the JSON format we are using in QT and QG2, we should discuss what the best data format could be and stick to it ;p
- References to qt operators, transitions, etc. from the Vue front-end have been removed and it feels much nicer to have a single point of comm. Still need to fix EncyclopediaBoard.
- EncyclopediaBoard and Board are very similar and it might be a good idea to have only one of them to avoid duplication.

Waiting for your comments!

2020-09-05 12:31 UTC, stared commented on src/components/AppButton.vue
> +  // @Prop() readonly hoverColor!: string
How is it related to performance? 
AND
If anything, we delete things, not comment them.

2020-09-05 12:32 UTC, stared commented on src/components/EncyclopediaPage/EncyclopediaBoard.vue
> +        polarization: 'v',
I guess capital `'V'`

2020-09-05 12:33 UTC, stared commented on src/components/GamePage/index.vue
> +import { IAbsorption } from 'quantum-tensors/dist/interfaces'
Not sure if it is a correct import.

2020-09-05 12:35 UTC, stared commented on src/components/GamePage/index.vue
> +    return uniq(result)
Never use `forEach` / `push` when you can use `map` (or `flatMap`) instead.

2020-09-05 12:36 UTC, stared commented on src/components/GamePage/index.vue
> +      return Particle.importParticle(iparticle)
Remove `{` and `return`.

2020-09-05 12:38 UTC, stared commented on src/engine/Element.ts
> +import { Elem, Group } from './interfaces'
i would go for `@/engine/interfaces` for consistency.

2020-09-05 12:39 UTC, sneakyweasel commented on src/components/AppButton.vue
> +  // @Prop() readonly hoverColor!: string
Will delete it, it left a linter error.

2020-09-05 12:41 UTC, sneakyweasel commented on src/components/EncyclopediaPage/EncyclopediaBoard.vue
> +        polarization: 'v',
I'm having trouble to understand how the indicator differs from the "normal" Board here, do you think we could use only one board or is there too much specific code?

2020-09-05 12:43 UTC, stared requested changes
Separation going in the right way.

Some things (e.g. `push` should be the last resort, we already discussed that).

The current code has errors in CI.

2020-09-05 12:52 UTC, stared commented
Things like unifying Boards for game and encyclopedia - clearly another PR (with which I would like to wait for @Frizi input - as a lot of things on board, especially related to interaction, may need serious refactoring).

2020-09-06 12:25 UTC, sneakyweasel commented on src/components/GamePage/index.vue
> +import { IAbsorption } from 'quantum-tensors/dist/interfaces'
Right now there's a mismatch between IAbsorption in QT and QG2, one using Coord and the other x, y. Will write a post on Basecamp about those issues.

2020-09-06 14:59 UTC, sneakyweasel commented
Everything seems to be working fine expect the indicator for bra-ket-view which somehow breaks and gives a strange error whose only reference is https://github.com/microsoft/TypeScript/issues/28102

2020-09-06 21:50 UTC, sneakyweasel commented
Everything seems to be working fine. CI tests are passing.

2020-09-07 09:04 UTC, Frizi requested changes

2020-09-07 09:07 UTC, Frizi commented
> Things like unifying Boards for game and encyclopedia - clearly another PR (with which I would like to wait for @Frizi input - as a lot of things on board, especially related to interaction, may need serious refactoring).

I'm all for it :) As you said, I wouldn't hold this PR back in wait for that change, but I'd definitely like to get rid of redundancy here.

2020-09-07 09:08 UTC, Frizi commented on src/components/GamePage/GameGraph.vue
> +          <!-- <text class="nodeText" :x="node.x" :y="node.y + 4" text-anchor="middle">{{ node.label }}</text> -->
unnecessary commented code

2020-09-07 15:50 UTC, stared commented
I tried to test it locally, but there is no visible speedup. 

(Plus, it did add a multiverse graph. @sneakyweasel, was it an intended change?)

2020-09-07 17:48 UTC, stared commented
There are some conflicts, could you rebase (or at least merge fix conflicts, then I will squash-rebase this part).

<img width="909" alt="Screenshot 2020-09-07 at 19 47 10" src="https://user-images.githubusercontent.com/1001610/92410015-fd6aec80-f142-11ea-8931-705cd691af0f.png">

2020-09-07 20:13 UTC, stared approved these changes

2020-09-07 20:15 UTC, merged