Homepage updates
Quantum-Game/quantum-game-2 pull request #238
Opened 2020-10-03 10:14 UTC by stared

@KlemKlem it is on the way to make it more up-to-date, more like a landing page of a startup, rather than a post-CQT project. 

Feel free to edit, @KlemKlem. I intend to have here:

- [ ] testimonials and team members in faces-in-circles, alike in slides,
- [ ] interactive Mach-Zehnder and BraKetVue
- [ ] much cleaner and clearer value proposition

<img width="951" alt="Screenshot 2020-10-03 at 12 10 55" src="https://user-images.githubusercontent.com/1001610/94988992-a6a1d880-0571-11eb-9d81-bd22d8ba4c46.png">

2020-10-04 13:37 UTC, stared commented
Added interactive Mach-Zehnder.

<img width="654" alt="Screenshot 2020-10-04 at 15 34 33" src="https://user-images.githubusercontent.com/1001610/95017103-80566880-0657-11eb-9f9b-5dd3338d8578.png">

2020-10-05 12:41 UTC, Frizi requested changes

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/HomepageInteractive.vue
> +    <a href="https://quantumgame.io/info/beam-splitter" target="_blank">Faraday Rotator</a>
the url should be relative, and also actually lead to faraday rotator page :)

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/HomepageInteractive.vue
> +export default class HomepageInteractive extends Vue {
please use `defineComponent` instead of class components.

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/HomepageSocial.vue
> +export default class HomepageSocial extends Vue {}
again, please don't use class components. I believe this whole script block can be removed in this case.

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/HomepageTestimonials.vue
> +export default class HomepageTestimonials extends Vue {
`defineComponent` instead of class components

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/index.vue
>  export default class HomePage extends Vue {
`defineComponent` instead of class components. I know this one was there before, but it could be changed anyway, as it is a small one.

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/HomepageAuthors.vue
> +export default class HomepageAuthors extends Vue {}
`defineComponent` instead of class components, or else script block can probably be removed completely

2020-10-05 12:41 UTC, Frizi commented on src/components/HomePage/HomepageHistory.vue
> +export default class HomepageHistory extends Vue {}
`defineComponent` instead of class components, or else script block can probably be removed completely

2020-10-06 07:53 UTC, stared commented
Tried this column layout, but it is "row first", and I couldn't find a way to make it "column first".

<img width="654" alt="Screenshot 2020-10-04 at 15 34 33" src="https://user-images.githubusercontent.com/1001610/95173794-7482b780-07b9-11eb-8248-8967f8ab5de7.png">

2020-10-06 11:43 UTC, Frizi requested changes

2020-10-06 11:43 UTC, Frizi commented on src/components/HomePage/HomepageTestimonials.vue
> +      <div v-for="t in testimonials" :key="t.name" layout="row u1">
```suggestion
    <div layout="row u4">
      <div v-for="t in testimonials" :key="t.name" layout="column u1">
```

i believe you want the "row" and "column" swapped here, to have a "row of columns" instead of "column of rows" here.

2020-10-06 11:43 UTC, Frizi commented on src/components/HomePage/HomepageTestimonials.vue
> +          ><b>{{ t.name }}</b> ({{ t.institute }})</span
```suggestion
        <span><b>{{ t.name }}</b> ({{ t.institute }})</span 
```

All sibling elements with `flex` will split any remaining (not taken by non-flex elements) space evenly between each other.

Either the `flex` on the name is not necessary, as you don't want the name to always take half of the space, or you can get rid of both `flex`es and keep the element's natural height for both text and name.

2020-10-06 11:43 UTC, Frizi commented on src/components/HomePage/HomepageTestimonials.vue
> +        href="https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22quantum+game+with+photons%22&btnG="
please encode the ampersands in URL. HTML attributes must be encoded.
```suggestion
        href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C5&amp;q=%22quantum+game+with+photons%22&amp;btnG="
```

Alternatively you can use vue-specific syntax and treat it as javascript string
```suggestion
        :href="'https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22quantum+game+with+photons%22&btnG='"
```

2020-10-06 11:43 UTC, Frizi commented on src/components/HomePage/HomePageLayout.vue
> +<script lang="ts"></script>
```suggestion
```

You don't need the `<script>` tag at all in cases like this.

2020-10-06 12:18 UTC, stared commented
It was my first approach, but it had another problem:

<img width="882" alt="Screenshot 2020-10-06 at 14 15 30" src="https://user-images.githubusercontent.com/1001610/95200362-8b87d080-07de-11eb-96f9-266df101ef32.png">

@Frizi could you take over this PR, and make these changes? I think it would be more efficient than being lead (I would be happy to see changes).

2020-10-06 15:41 UTC, stared commented
<img width="1105" alt="Screenshot 2020-10-06 at 17 39 59" src="https://user-images.githubusercontent.com/1001610/95224465-fe06a980-07fa-11eb-89a8-ef2663ba26d3.png">

I put images in `public` (`src/assets` didn't work for some reason; solutions from https://stackoverflow.com/questions/51812496/vue-cli-3-use-background-image-in-style-tag didn't help).

2020-10-06 15:44 UTC, merged